version: '3'
services:
    mongodb:
        image: mongo
        ports:
            - 27018:27017

    node1:
        build:
            dockerfile: ./docker/nest.dockerfile
            context: .
        container_name: nest-1
        environment:
            MONGO_URL: mongodb://mongodb:27017
        ports:
            - "3000:3000"
        depends_on:
            - "mongodb"
